export default [
  { value: 'Canadian', label: 'Canadian' },
  { value: 'CertClean', label: 'CertClean' },
  { value: 'Chemical Free', label: 'Chemical Free' },
  { value: 'Dairy Free', label: 'Dairy Free' },
  { value: 'EWG Verified', label: 'EWG Verified' },
  { value: 'EcoCert', label: 'EcoCert' },
  { value: 'Fair Trade', label: 'Fair Trade' },
  { value: 'Gluten Free', label: 'Gluten Free' },
  { value: 'Hypoallergenic', label: 'Hypoallergenic' },
  { value: 'Natural', label: 'Natural' },
  { value: 'No Talc', label: 'No Talc' },
  { value: 'Non-GMO', label: 'Non-GMO' },
  { value: 'Organic', label: 'Organic' },
  { value: 'Peanut Free Product', label: 'Peanut Free Product' },
  { value: 'Sugar Free', label: 'Sugar Free' },
  { value: 'USDA Organic', label: 'USDA Organic' },
  { value: 'Vegan', label: 'Vegan' },
  { value: 'alcohol free', label: 'alcohol free' },
  { value: 'cruelty free', label: 'cruelty free' },
  { value: 'oil free', label: 'oil free' },
  { value: 'purpicks', label: 'purpicks' },
  { value: 'silicone free', label: 'silicone free' },
  { value: 'water free', label: 'water free' },
];
